volumes:
  grafana_storage:
    name: grafana_storage

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana_storage:/var/lib/grafana
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - the-piot
    depends_on:
      - mysql

networks:
  the-piot:
    name: the-piot
    external: true
